#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mozjs38
Version  : 38.2.1.0
Release  : 4
URL      : https://people.mozilla.org/~sstangl/mozjs-38.2.1.rc0.tar.bz2
Source0  : https://people.mozilla.org/~sstangl/mozjs-38.2.1.rc0.tar.bz2
Summary  : psutil is a cross-platform library for retrieving information onrunning processes and system utilization (CPU, memory, disks, network)in Python.
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause BSD-3-Clause BSD-3-Clause-Clear GPL-2.0 LGPL-2.0 LGPL-2.1 MIT MPL-2.0-no-copyleft-exception
Requires: mozjs38-bin
Requires: psutil
Requires: py
Requires: pyOpenSSL
Requires: pyasn1
Requires: pytest
Requires: pytest-cov
Requires: wheel
BuildRequires : icu4c-dev
BuildRequires : nspr-dev
BuildRequires : pbr
BuildRequires : pip
BuildRequires : pkgconfig(libffi)
BuildRequires : pkgconfig(x11)
BuildRequires : psutil
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : zlib-dev
Patch1: pytest.patch
Patch2: python.patch
Patch3: install-copy-files.patch

%description
This directory contains SpiderMonkey 38.
This release is based on a revision of Mozilla 38:
http://hg.mozilla.org/releases/
The changes in the patches/ directory were applied.

%package bin
Summary: bin components for the mozjs38 package.
Group: Binaries

%description bin
bin components for the mozjs38 package.


%package dev
Summary: dev components for the mozjs38 package.
Group: Development
Requires: mozjs38-bin
Provides: mozjs38-devel

%description dev
dev components for the mozjs38 package.


%prep
%setup -q -n mozjs-38.0.0
%patch1 -p1
%patch2 -p1
%patch3 -p1

%build
export LANG=C
export SOURCE_DATE_EPOCH=1491681638
pushd js/src
%configure --disable-static --with-x \
--with-system-zlib \
--enable-system-ffi \
--without-system-nspr \
--without-system-icu \
--without-intl-api \
--enable-threadsafe \
--enable-shared-js \
--enable-gcgenerational
make V=1  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1491681638
rm -rf %{buildroot}
pushd js/src
%make_install
popd
## make_install_append content
mv %{buildroot}/usr/lib64/pkgconfig/js.pc %{buildroot}/usr/lib64/pkgconfig/mozjs38.pc
## make_install_append end

%files
%defattr(-,root,root,-)
/usr/lib64/libjs_static.ajs

%files bin
%defattr(-,root,root,-)
/usr/bin/js
/usr/bin/js-config

%files dev
%defattr(-,root,root,-)
/usr/include/mozjs-38/js-config.h
/usr/include/mozjs-38/js.msg
/usr/include/mozjs-38/js/CallArgs.h
/usr/include/mozjs-38/js/CallNonGenericMethod.h
/usr/include/mozjs-38/js/CharacterEncoding.h
/usr/include/mozjs-38/js/Class.h
/usr/include/mozjs-38/js/Conversions.h
/usr/include/mozjs-38/js/Date.h
/usr/include/mozjs-38/js/Debug.h
/usr/include/mozjs-38/js/GCAPI.h
/usr/include/mozjs-38/js/HashTable.h
/usr/include/mozjs-38/js/HeapAPI.h
/usr/include/mozjs-38/js/Id.h
/usr/include/mozjs-38/js/LegacyIntTypes.h
/usr/include/mozjs-38/js/MemoryMetrics.h
/usr/include/mozjs-38/js/Principals.h
/usr/include/mozjs-38/js/ProfilingFrameIterator.h
/usr/include/mozjs-38/js/ProfilingStack.h
/usr/include/mozjs-38/js/Proxy.h
/usr/include/mozjs-38/js/RequiredDefines.h
/usr/include/mozjs-38/js/RootingAPI.h
/usr/include/mozjs-38/js/SliceBudget.h
/usr/include/mozjs-38/js/StructuredClone.h
/usr/include/mozjs-38/js/TracingAPI.h
/usr/include/mozjs-38/js/TrackedOptimizationInfo.h
/usr/include/mozjs-38/js/TypeDecls.h
/usr/include/mozjs-38/js/UbiNode.h
/usr/include/mozjs-38/js/UbiNodeTraverse.h
/usr/include/mozjs-38/js/Utility.h
/usr/include/mozjs-38/js/Value.h
/usr/include/mozjs-38/js/Vector.h
/usr/include/mozjs-38/js/WeakMapPtr.h
/usr/include/mozjs-38/jsalloc.h
/usr/include/mozjs-38/jsapi.h
/usr/include/mozjs-38/jsbytecode.h
/usr/include/mozjs-38/jsclist.h
/usr/include/mozjs-38/jscpucfg.h
/usr/include/mozjs-38/jsfriendapi.h
/usr/include/mozjs-38/jsperf.h
/usr/include/mozjs-38/jsprf.h
/usr/include/mozjs-38/jsprototypes.h
/usr/include/mozjs-38/jspubtd.h
/usr/include/mozjs-38/jstypes.h
/usr/include/mozjs-38/jsversion.h
/usr/include/mozjs-38/jswrapper.h
/usr/include/mozjs-38/mozilla/Alignment.h
/usr/include/mozjs-38/mozilla/AllocPolicy.h
/usr/include/mozjs-38/mozilla/AlreadyAddRefed.h
/usr/include/mozjs-38/mozilla/Array.h
/usr/include/mozjs-38/mozilla/ArrayUtils.h
/usr/include/mozjs-38/mozilla/Assertions.h
/usr/include/mozjs-38/mozilla/Atomics.h
/usr/include/mozjs-38/mozilla/Attributes.h
/usr/include/mozjs-38/mozilla/BinarySearch.h
/usr/include/mozjs-38/mozilla/BloomFilter.h
/usr/include/mozjs-38/mozilla/Casting.h
/usr/include/mozjs-38/mozilla/ChaosMode.h
/usr/include/mozjs-38/mozilla/Char16.h
/usr/include/mozjs-38/mozilla/CheckedInt.h
/usr/include/mozjs-38/mozilla/Compiler.h
/usr/include/mozjs-38/mozilla/Compression.h
/usr/include/mozjs-38/mozilla/Constants.h
/usr/include/mozjs-38/mozilla/DebugOnly.h
/usr/include/mozjs-38/mozilla/Decimal.h
/usr/include/mozjs-38/mozilla/Endian.h
/usr/include/mozjs-38/mozilla/EnumSet.h
/usr/include/mozjs-38/mozilla/EnumeratedArray.h
/usr/include/mozjs-38/mozilla/FloatingPoint.h
/usr/include/mozjs-38/mozilla/GuardObjects.h
/usr/include/mozjs-38/mozilla/HashFunctions.h
/usr/include/mozjs-38/mozilla/IntegerPrintfMacros.h
/usr/include/mozjs-38/mozilla/IntegerRange.h
/usr/include/mozjs-38/mozilla/IntegerTypeTraits.h
/usr/include/mozjs-38/mozilla/IteratorTraits.h
/usr/include/mozjs-38/mozilla/JSONWriter.h
/usr/include/mozjs-38/mozilla/Likely.h
/usr/include/mozjs-38/mozilla/LinkedList.h
/usr/include/mozjs-38/mozilla/LinuxSignal.h
/usr/include/mozjs-38/mozilla/MacroArgs.h
/usr/include/mozjs-38/mozilla/MacroForEach.h
/usr/include/mozjs-38/mozilla/MathAlgorithms.h
/usr/include/mozjs-38/mozilla/Maybe.h
/usr/include/mozjs-38/mozilla/MaybeOneOf.h
/usr/include/mozjs-38/mozilla/MemoryChecking.h
/usr/include/mozjs-38/mozilla/MemoryReporting.h
/usr/include/mozjs-38/mozilla/Move.h
/usr/include/mozjs-38/mozilla/NullPtr.h
/usr/include/mozjs-38/mozilla/NumericLimits.h
/usr/include/mozjs-38/mozilla/Pair.h
/usr/include/mozjs-38/mozilla/PodOperations.h
/usr/include/mozjs-38/mozilla/Poison.h
/usr/include/mozjs-38/mozilla/Range.h
/usr/include/mozjs-38/mozilla/RangedPtr.h
/usr/include/mozjs-38/mozilla/ReentrancyGuard.h
/usr/include/mozjs-38/mozilla/RefCountType.h
/usr/include/mozjs-38/mozilla/RefPtr.h
/usr/include/mozjs-38/mozilla/ReverseIterator.h
/usr/include/mozjs-38/mozilla/RollingMean.h
/usr/include/mozjs-38/mozilla/SHA1.h
/usr/include/mozjs-38/mozilla/Scoped.h
/usr/include/mozjs-38/mozilla/SegmentedVector.h
/usr/include/mozjs-38/mozilla/SizePrintfMacros.h
/usr/include/mozjs-38/mozilla/SplayTree.h
/usr/include/mozjs-38/mozilla/TaggedAnonymousMemory.h
/usr/include/mozjs-38/mozilla/TemplateLib.h
/usr/include/mozjs-38/mozilla/ThreadLocal.h
/usr/include/mozjs-38/mozilla/ToString.h
/usr/include/mozjs-38/mozilla/TypeTraits.h
/usr/include/mozjs-38/mozilla/TypedEnumBits.h
/usr/include/mozjs-38/mozilla/Types.h
/usr/include/mozjs-38/mozilla/UniquePtr.h
/usr/include/mozjs-38/mozilla/Vector.h
/usr/include/mozjs-38/mozilla/WeakPtr.h
/usr/include/mozjs-38/mozilla/double-conversion.h
/usr/include/mozjs-38/mozilla/unused.h
/usr/include/mozjs-38/mozilla/utils.h
/usr/lib64/libmozjs-38.so
/usr/lib64/pkgconfig/mozjs38.pc
